### ISSUE TITLE
Latest version not updated when new snapshot (base)version is deployed

### ISSUE THREAD

**Issue by nefilim** [arktekk/sbt-aether-deploy#21]
This is happening with the latest version of Nexus:

https://issues.sonatype.org/browse/NEXUS-6551

Still waiting for Sonatype to respond fully but at first glance they question the client side. 

Just to be clear, when uploading new builds of the same snapshot base version, the latest information is updated correctly.

**Comment by tarrall** [comment]
Just wanted to add a comment here in case anyone else gets bitten by this.

If your root issue is that you need your Nexus repo to resolve "v=LATEST" correctly, via an endpoint like "/service/local/artifact/maven/resolve?g=com.example&a=foobar_2.10&e=jar&v=LATEST"...

... the solution is to remove the "latest" field from the maven-metadata.xml file on the repo.  Nexus doesn't need that field in order for the resolver to find v=LATEST and sbt-aether-deploy won't add it if it's not there.

I'm not sure what causes Nexus to add that field -- I think I've seen it happen after a "metadata rebuild" on the nexus server but there may be other causes.

In any case, if you find v=LATEST isn't working, the issue probably isn't "sbt stopped updating the <latest> field in maven-metadata.xml" but rather "somehow that field got added and needs to be removed."
