### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.http.conn.ssl.SSLSocketFactory on publish

### ISSUE THREAD

**Issue by bretthoerner** [arktekk/sbt-aether-deploy#25]
Using `sbt 0.13.5` and `aether-deploy 0.13`.

```
> +publish
[info] Setting version to 2.10.0
[info] Set current project to zookeeper-utils (in build file:/home/brett/Development/mr/scala-utils/)
[info] Wrote /home/brett/Development/mr/scala-utils/zookeeper-utils/target/scala-2.10/zookeeper-utils_2.10-2.0.2.pom
[warn] No credentials supplied for nexus.massrel.com
[trace] Stack trace suppressed: run last zookeeper-utils/*:publish for the full output.
[error] (zookeeper-utils/*:publish) java.lang.NoSuchMethodError: org.apache.http.conn.ssl.SSLSocketFactory.<init>(Ljavax/net/ssl/SSLSocketFactory;Lorg/apache/http/conn/ssl/X509HostnameVerifier;)V
[error] Total time: 0 s, completed Aug 27, 2014 10:51:07 AM
```

**Comment by LoranceChen** [comment]
I'm encounter a **[error] Could not find metadata xxxx.xml in releases (https://oss.sonatype.org/service/local/staging/deploy/maven2)** when execute sbt publish.  
But the command's result is **success**.   
When I attempt `close` the repository in oss.sonatype.org to release it, a signature validate error occurred. I find the content not exist any .asc file. Hope some help. Thanks

**Comment by hamnis** [comment]
`sbt publish` does not do what you think it does. Take a look at sbt-pgp and `publish-signed`
