### ISSUE TITLE
Why no metadata for SBT plugins?

### ISSUE THREAD

**Issue by gregsymons** [arktekk/sbt-aether-deploy#26]
I'm sure there's a good reason for it but in [Booter.scala:33-36](https://github.com/arktekk/sbt-aether-deploy/blob/master/src/main/scala/aether/Booter.scala#L33-L36), you explicitly do not add the metadata generators if it's a plugin build. This means that not only does no metadata get generated and uploaded for SBT plugins, but `SNAPSHOT` builds aren't given unique versions. Is there something I'm missing?

**Comment by custommonkey** [comment]
Any workarounds for this?
