### ISSUE TITLE
aether-deploy fails because 'pom' artifact is deployed twice

### ISSUE THREAD

**Issue by y0un5** [arktekk/sbt-aether-deploy#33]
In 0.16, aether-deploy fails with 'Bad Request (400)'. This is caused by the following codes.

```scala
// master/src/main/scala/aether/Plugin.scala
def createArtifact(artifacts: Map[Artifact, sbt.File], pom: sbt.File, coords: MavenCoordinates, mainArtifact: File): AetherArtifact = {
  val filtered = artifacts.filterNot {
     case (a, f) => a.classifier.isEmpty && f == mainArtifact
  }
  val subArtifacts = AetherSubArtifact(pom, None, "pom") +: filtered.foldLeft(Vector[AetherSubArtifact]()) { case (seq, (a, f)) => AetherSubArtifact(f, a.classifier, a.extension) +: seq}
```

'pom' artifact is included in both `filtered` and `subArtifacts`, so it is deployed twice. This causes 'Bad Request (400)' when executing aether-deploy.

**Comment by hamnis** [comment]
Please test https://oss.sonatype.org/content/repositories/noarktekk-1047

Will close and release the repo when approved.

**Comment by y0un5** [comment]
It works! Thanks.

**Comment by hamnis** [comment]
Released, should be in maven central in about 10 minutes.
