### ISSUE TITLE
aether-deploy ignores SBT artifact config

### ISSUE THREAD

**Issue by F30** [arktekk/sbt-aether-deploy#36]
For a project, we're trying to just publish the fat JAR from sbt-assembly instead of the a thin JAR. As described [in the SBT docs](http://www.scala-sbt.org/0.13/docs/Artifacts.html#Publishing+.war+files), we use the following line to omit the thin JAR from publishing:

    publishArtifact in (Compile, packageBin) := false

However, this does not park with aether-deploy and the thin JAR still gets published. Is this the intended behavior or a bug? If it's intended, is there a possible workaround?

**Comment by hamnis** [comment]
So you want to replace the main artifact with the assembly artifact?

The "thin" jar, is the main artifact of the deployment, and Maven requires a Main artifact.
if you want to replace which artifact is used as the main artifact you can add this in your build file:

```scala
import aether.AetherKeys._

aetherPackageMain := assembly
```

**Comment by F30** [comment]
Yes, exactly.

Thanks for your solution! It works great, but I had to slightly tweak it in order to make type and operator match:

    aetherPackageMain <<= assembly

The `publishArtifact in (Compile, packageBin)` line from my original approach is still required additionally.

**Comment by F30** [comment]
… or even nicer, using SBT 0.13 format:

    aetherPackageMain := assembly.value

**Comment by svsatheeshkumar** [comment]
I tried this options and its not working. Anyting I am missing. 

aetherPackageMain := assembly.value
