### ISSUE TITLE
Get the artifact upload url

### ISSUE THREAD

**Issue by SagarN** [arktekk/sbt-aether-deploy#39]
As part of CD, I would like to extract the artifact upload url. I then can use the upload url for CD process. Is there a way to do so ?

**Comment by hamnis** [comment]
the path is deterministic. you can look at the aetherCoordinates for that.

I suggest creating a new task that fetches the coordinates and builds the URI based on that.

**Comment by SagarN** [comment]
Thanks for the pointer !!, worked
