### ISSUE TITLE
Aether-deploy plugin does not use SNI with SSL maven repos

### ISSUE THREAD

**Issue by Yachironi** [arktekk/sbt-aether-deploy#40]
Similar bug: https://issues.jenkins-ci.org/browse/JENKINS-38738

**Comment by hamnis** [comment]
Probably fixed with upgrade of Aether.

**Comment by hamnis** [comment]
There is no newer version of Aether.

Are you using Wagon as the transport?

**Comment by hamnis** [comment]
Seems like this has something to with the Apache Httpclient version. 

I'll change this to use the takari okhttp transport for http, and see if this helps.

**Comment by Yachironi** [comment]
No i'm not using wagon, i'am using only sbt-aether-deploy to deploy.
Please let me know when you need to test it after making the fix.

**Comment by hamnis** [comment]
Seems like the takari thing only works if you use maven :(

I'll try upgrading httpclient and see if that works.

**Comment by hamnis** [comment]
@Yachironi can you please test if  PR #42  works for you?

**Comment by hamnis** [comment]
@Yachironi hello?

**Comment by hamnis** [comment]
@Yachironi did you test this?
