### ISSUE TITLE
Wagon/WebDAV support removed?

### ISSUE THREAD

**Issue by capotej** [arktekk/sbt-aether-deploy#51]
Hi! I noticed that Wagon/WebDAV support was temporarily removed in this commit: https://github.com/arktekk/sbt-aether-deploy/commit/f9191b0b7c2653e0e9b730a45cf7378beb536642

I'm assuming it was removed due to an incompatibility introduced by bumping/upgrading library versions, like maven to 3.5.0. I'm happy to help out and contribute to fixing this, just wanted to know why it was removed first.

Thanks for all your work on this library btw, it's very useful.

**Comment by hamnis** [comment]
I couldnt find a version combination of things that made webdav work. So I would happily accept help with regards to that.

**Comment by hamnis** [comment]
Not a strong demand for this, closing.
