### ISSUE TITLE
deploying to nexus repository management uploads pom, src, and doc but no jar

### ISSUE THREAD

**Issue by xelax** [arktekk/sbt-aether-deploy#52]
For some reason publishing to our internal nexus repository started failing (i suspect nexus was updated, but anyhow) in particular the pom, src and doc go though but the uploading of the jar fails with return value "400": 

org.eclipse.aether.deployment.DeploymentException: Failed to deploy artifacts: Could not transfer artifact XXXXX:platform-spark_2.11:jar:2.0.0-20180607.172350-2 from/to XXX Central Snapshots (http://XXXXXXXX/content/repositories/snapshots): Bad Request (400)

The worse part is that since the pom goes through this leaves the repo in a broken state. I can deploy without problem the same build if I use maven:

mvn deploy:deploy-file \
   -Durl=http:/XXXXX/content/repositories/snapshots/ \
   -Dfile=./jars/mycommercial.jar \
   -DpomFile=./jars/mycommercial.pom \
   -Dsources=./jars/mycommercial-sources.jar \
   -Djavadoc=./jars/mycommercial-javadoc.jar

I am puzzled by the the issue, but I would like to suggest that the plugin should start the deployment from the jar file and stop if it fails to avoid leaving the repository in a corrupted state.

Thank you!

**Comment by hiteshjm** [comment]
Any updates on this. I am getting the same.
