### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by mberndt123** [arktekk/sbt-aether-deploy#53]
Hi,

thank you for creating this project. We would like to use it in our company, however corporate policy forbids us from using projects without a license. Could you add one?

sbt uses the Apache 2.0 license, so that would probably be an appropriate choice for your project as well.
https://github.com/sbt/sbt/blob/develop/LICENSE

**Comment by hamnis** [comment]
This is apache2 licensed already.
Apparently we have forgotten to add the LICENSE file to the repo.

https://github.com/arktekk/sbt-aether-deploy/blob/master/publish.sbt#L38

**Comment by mberndt123** [comment]
Oh, I see! Thanks for clearing this up. I guess it would be a good idea to add the license file to the repo, right?

**Comment by hamnis** [comment]
yeah.
I'll try to get around to adding it soon.
