### ISSUE TITLE
How to skip a (root-)module in publish or aetherDeploy

### ISSUE THREAD

**Issue by ThijsBroersen** [arktekk/sbt-aether-deploy#66]
I tried 
```
skip in aetherDeploy := true,
skip in publish := true
```
it still tries to publish the module(s)

**Comment by ThijsBroersen** [comment]
I added 
```
publish := {},
aetherDeploy := {}
```
to clear the tasks in those modules

**Comment by Isammoc** [comment]
@ThijsBroersen 

I had the same question.
Indeed, now sbt use `publish / skip` to decide if the current project should "skip" or not the "publish" task.
Seems that plugin still use the `publishArtifact` settings

Try to set 

```scala
Compile / publishArtifact := false
```

Ref: [src/main/scala/aether/Plugin.scala#L78](https://github.com/arktekk/sbt-aether-deploy/blob/master/aether-deploy/src/main/scala/aether/Plugin.scala#L78)

**Comment by hamnis** [comment]
we now also support `skip in publish := true`
