### ISSUE TITLE
JDK8 Support

### ISSUE THREAD

**Issue by purijatin** [arktekk/sbt-aether-deploy#71]
I am unable to use the plugin (0.27.0) with my project that is still on JDK8. My guess is that 0.27.0 was built using JDK11.

0.26.0 worked with my project. 

It would be a request if we can still remain on JDK8 for another year or so. This is usually a pain point with Spark-based projects, which are now slowly moving towards JDK11. But still needs time. 

Thanks for the great work.

**Comment by arashi01** [comment]
@hamnis This has also just bit me. Is there any chance you could publish a 0.28.0 built on JDK8?
